src/HTML5/Parser/Scanner.php
The english alphabet does not allow the substitution of a lowercase z in place of another uppercase A.
=> Fixed alphabet, &szlig; now can be detected

README.md, RELEASE.md, src/HTML5/Parser/DOMTreeBuilder.php, test/HTML5/Parser/DOMTreeBuilderTest.php
Closes https://github.com/Masterminds/html5-php/pull/69
~~[This](https://github.com/Masterminds/html5-php/compare/feature/domquery-options) change has to be integrated~~
=> HTML parsing options

.travis.yml
See: https://travis-ci.org/Masterminds/html5-php/builds/57083554
PHP interpreter| test suite results
------------ | -------------
PHP 5.6|Time: 14.27 seconds, Memory: 20.25Mb
PHP HHVM| Time: 4.64 seconds, Memory: 16.15Mb
PHP 7| Time: **157 ms**, Memory: 6.00Mb
Does it mean that PHP7 is 90x faster? :scream: :scream: :scream: :scream: :scream:
=> Support for PHP7

src/HTML5/Parser/UTF8Utils.php
On shared hosts, `ini_set` is often disabled by the administrator. The `mbstring` extension provides an accessor function `mb_substitute_character`, so we should use that instead.
=> Use mb_substitute_character inset of ini_set

src/HTML5/Elements.php, test/HTML5/Parser/DOMTreeBuilderTest.php
When JavaScript is disabled noscript tags become transparent to
to the DOM. For more details see:
https://w3c.github.io/html/semantics-scripting.html#the-noscript-element
While this notes limitations in the values in the head there are
different sets elsewhere such as in:
https://w3c.github.io/html/syntax.html#the-in-head-noscript-insertion-mode
Since this is not a validating parser this handling it to make it
transparent.
=> Fixes #98: a DOM is allowed within noscript tags

src/HTML5/Serializer/OutputRules.php, test/HTML5/Serializer/OutputRulesTest.php
When outputting a `TEXT_RAW` node, OutputRules will occasionally throw the PHP Notice `Undefined property: DOMElement::$data`.
This seems to happen when processing HTML that doesn't strictly conform to spec (my test case had child nodes inside an `iframe`), however we can prevent the issue by type checking the node before accessing the `data` property
=> Fix PHP Notice in OutputRules

.travis.yml, src/HTML5/Parser/Tokenizer.php, test/benchmark/example.html, test/benchmark/run.php
this is an alternative version of https://github.com/Masterminds/html5-php/pull/130 (thanks @MichaelHeerklotz)
It takes the same approach but it does not change method signatures
I've added also a basic benchmark:
Before:
```
Loading: 234.88136053085
Writing: 29.471714496613
```
After:
```
Loading: 189.25537729263
Writing: 30.500716209412
```
Performance change looks the same (20%)
@MichaelHeerklotz can you try it on your dataset?
=> Tokenizer performance

src/HTML5/Parser/Tokenizer.php, test/HTML5/Parser/DOMTreeBuilderTest.php, test/HTML5/Parser/TokenizerTest.php
Fixes #124 
Tries to implement the HTML spec: 
https://www.w3.org/TR/html52/syntax.html#character-reference-state
More specifically:
> If the character reference was consumed as part of an attribute (return state is either attribute value (double-quoted) state, attribute value (single-quoted) state or attribute value (unquoted) state), and the last character matched is not a U+003B SEMICOLON character (;), and the next input character is either a U+003D EQUALS SIGN character (=) or an alphanumeric ASCII character, then, for historical reasons, switch to the character reference end state.
=> Raw & in attributes

src/HTML5/Parser/DOMTreeBuilder.php, src/HTML5/Parser/Tokenizer.php, test/HTML5/Parser/DOMTreeBuilderTest.php, test/HTML5/Parser/TokenizerTest.php
This fixes #136.
See also: https://www.w3.org/TR/html5/syntax.html#start-tags
=> Respect self-closing tags only on foreign elements

composer.json
Even if the DOM extension is usually included in packaged versions of PHP, technically, a PHP build may not have it installed or enabled. Adding a constraint in Composer could prevent runtime issues.
Don't close to ignore this PR if you don't think it's useful :) .
=> Add DOM extension in composer.json

README.md, composer.json, src/HTML5.php, src/HTML5/Parser/DOMTreeBuilder.php, src/HTML5/Parser/FileInputStream.php, src/HTML5/Parser/StringInputStream.php, src/HTML5/Parser/Tokenizer.php, src/HTML5/Parser/TreeBuildingRules.php, src/HTML5/Parser/UTF8Utils.php
This PR proposes a few things:
- add ctype, iconv and mbstring extensions in composer.json for the same reason as the DOM extension ;
- improve several phpdocs by adding more detailed information on types and arguments
- remove a few unused variables
- fix a few bugs
Don't hesitate to answer my comments when you think I'm wrong :) !
=> Add more extensions on composer.json, improve phpdocs and remove dead code

src/HTML5/Parser/Tokenizer.php
After working on https://github.com/Masterminds/html5-php/pull/146, I realized the Tokenizer was the next bottleneck of the parser. This PR improves its performance by inlining text parsing and removing some Scanner::current calls.
As you can see in https://blackfire.io/profiles/8d809c0b-1a22-476e-9800-756d7e0440ba/graph (current 2.x branch), there are two main bottlenecks: `Scanner::current` (which is fixed by removing the InputStream in https://github.com/Masterminds/html5-php/pull/146) and `Tokenizer::consumeData`.
This PR improves the state of `Tokenizer::consumeData` by doing two things:
- removing unnecessary calls to `Scanner::current`;
- inlining the logic dedicated to characters parsing, as it is by far the most important execution path of the consumeData method;
This creates a …
=> Improve the Tokenizer performance

src/HTML5/Parser/Scanner.php, src/HTML5/Parser/Tokenizer.php
Improve performance by moving sequence matching to the string scanner (that has a raw access to the underlying string)
Running the `test/benchmark/run.php` benchmark:
```
Before this PR:
Loading: 106.80956840515
After this PR:
Loading: 100.03929138184
```
=> Improve performance by moving sequence matching

src/HTML5/Elements.php
`static::element($name)` already handles non-existent nodes, returning `0`, which won't match the mask (and so will return `false` as well).
This optimization removes 2 to 4 method calls per call to `isA` (which happens multiple times for end start tag, and once per end tag).
Before:
Loading: 113.14846754074
Writing: 36.459083557129
After:
Loading: 112.29121208191
Writing: 34.805071353912
=> Optimize the check for the element types during parsing

src/HTML5/Parser/Scanner.php, src/HTML5/Parser/Tokenizer.php
Places consuming whitespaces don't care about the matched substring. They either need  its length, or nothing.
Returning only the length directly avoids computing the substring.
Loading benchmark:
Before: 115.045773983
After: 112.26821184158
=> Optimize consuming whitespaces

src/HTML5/Parser/Tokenizer.php
Tokens are always a single char. Using strspn to find whether they belong to a fixed list is slower than comparing them directly.
Loading benchmark:
Before: 113.15485715866
After: 112.65460729599
That's not a huge difference, but it still helps.
=> Optimize the token comparison

src/HTML5/Parser/Tokenizer.php
Instead of handling each char one by one, we read them in batch until a char for which we need a special handling (chars ending the attribute value, references and chars needing to throw an error).
I ran the loading benchmark on a modified fixture file in which I unquoted all class attributes containing a single class (this kind of replacement was the easiest to do).
Before: 116.11662387848
After: 114.08836126328
There is no difference on the unmodified benchmark, because it uses quoted attributes everywhere.
=> Optimize the parsing of unquoted attributes

src/HTML5/Parser/Tokenizer.php
Here is a blackfire comparison of the loading of the fixture file used by the benchmark (I haven't profiled the whole benchmark, as repeating it 100 times leads to some functions being called thousands of millions of time, which makes the overhead of the profiler increase too much): https://blackfire.io/profiles/compare/0ad49ded-25b3-483b-aacd-3ccbc203db69/graph
=> Optimize main loop

src/HTML5/Parser/Tokenizer.php
Instead of processing the text token one by one in the main loop, it is now processed in batch until the next special token (< and & which have special handling in the main loop and NUL characters which need to report a parse error).
https://blackfire.io/profiles/compare/8d7277d0-e2ed-40cf-b9b6-bffa6a523ae6/graph
There is a 51% improvement there
=> Optimize the processing of text between nodes

src/HTML5.php, src/HTML5/Parser/UTF8Utils.php, test/HTML5/Fixtures/encoding/utf-8.html, test/HTML5/Fixtures/encoding/windows-1252.html, test/HTML5/Html5Test.php
Also fixes a few comments indentation.
=> Allow to pass a charset to the Scanner

src/HTML5/Parser/DOMTreeBuilder.php, test/HTML5/Parser/DOMTreeBuilderTest.php
Solves https://github.com/Masterminds/html5-php/issues/167 (If I am correct).
=> Set default encoding in the DOMDocument object

src/HTML5/Parser/DOMTreeBuilder.php, test/HTML5/Parser/DOMTreeBuilderTest.php
Normally, an end tag for a void element would simply be discarded,
but the spec includes a special rule as follows:
> An end tag whose tag name is "br"
> Parse error. Drop the attributes from the token, and act as
> described in the next entry; i.e. act as if this was a "br"
> start tag token with no attributes, rather than the end tag
> token that it actually is.
closes https://github.com/Masterminds/html5-php/issues/185
=> Add special case for end tag </br>. Fixes #185

src/HTML5.php
With the following reproducer:
```php
<?php
use Masterminds\HTML5;
require __DIR__.'/vendor/autoload.php';
cli_set_process_title('leak');
$html = file_get_contents('https://www.php.net/');
$html5 = new HTML5();
$dom = $html5->loadHTML($html);
echo "Converting to HTML 5\n";
for ($i=0; $i < 100; $i++) {
$html5->saveHTML($dom);
// printf("%.2f\n", memory_get_usage(false) / 1024 / 1024);
}
printf("%.2f\n", memory_get_usage(false) / 1024 / 1024);
```
Without my patch: 8.51
With my patch:    0.67
---
Note: there are another leak, but I can not find it for now...
But this patch is **really** mandatory!
=> Fixed memory leak in HTML5::saveHTML()

src/HTML5.php, src/HTML5/Serializer/OutputRules.php
Alternative implementation of https://github.com/Masterminds/html5-php/pull/188
it is substantially the same but using a separate method in the concrete class...
closes https://github.com/Masterminds/html5-php/pull/188
=> mitigate cyclic reference between output rules and the traverser objects

.gitattributes
So we can reduce the `prefer-dist` package download size.
=> Add .gitattributes file with export-ignore rules

src/HTML5/Parser/Tokenizer.php, test/HTML5/Html5Test.php
See first commit for failing test case.
Before:
```html
<a href="https://domain.com/page.php?foo=bar&target=baz">https://domain.com/page.php?foo=bar&target=baz</a>
```
After:
```html
<a href="https://domain.com/page.php?foo=bar&amp;target=baz">https://domain.com/page.php?foo=bar&amp;⌖=baz</a>
```
`consumeData` reads up to `&target`:
```php
$this->text .= $this->scanner->charsUntil("<&\0");
```
On next iteration, `&` is detected as a character reference:
```php
$tok = $this->scanner->current();
if ('&' === $tok) {
// Character reference
$ref = $this->decodeCharacterReference();
```
Input is valid HTML5 (https://validator.w3.org/#validate_by_input):
```html
<a href="https://domain.com/page.php?foo=bar&target=baz">https://domain.com/page.php?foo=bar&target=baz</a>
``` …
=> fix: query parameter parsed as character entity

.travis.yml, composer.json, phpunit.xml.dist, test/HTML5/Parser/TokenizerTest.php, test/HTML5/TestCase.php
=> Travis: Enable tests on PHP 8.0

src/HTML5/Parser/DOMTreeBuilder.php
Several DOM methods trigger a deprecation warning on PHP 8.1 if we pass `null` for a parameter that is expected to be a string. This PR should fix those issues by adding explicit string casts.
=> Fix PHP 8.1 deprecations

src/HTML5/Parser/Scanner.php, src/HTML5/Parser/Tokenizer.php, test/HTML5/Parser/TokenizerTest.php
* Correctly handle comment end bang state
* Avoid Scanner::peek reading beyond end of data
Fixes: #215
Fixes: #217
=> Address comment handling issues

README.md
just a typo fix: rentrance -> reentrance
=> doc(spelling): fix reentrance spelling in readme

composer.json, src/HTML5/Parser/Tokenizer.php
Even if 1-2% slower it does not depend on system locale as ctype functions. Polyfills are even slower.
Fixes #173
=> Get rid of ctype

src/HTML5/Elements.php, test/HTML5/ElementsTest.php
The `<video>` tag is incorrectly marked as a block element, while it's actually an inline one according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#list_of_inline_elements).
This causes the following problem:
```php
use Masterminds\HTML5;
$html5 = new HTML5();
$dom = $html5->loadHTMLFragment('<p>Test: <video><source src="/path/to/video.mp4" /></video></p>');
echo $html5->saveHTML($dom);
```
Result:
```html
<p>Test: </p><video><source src="/path/to/video.mp4"></video>
```
Even though having a `<video>` tag inside a `<p>` tag is valid HTML, it gets moved outside the `<p>` tag.
=> Mark `<video>` tag as inline element

src/HTML5/Parser/Tokenizer.php
ctype_alpha(false) triggers warning ctype_alpha(): Argument of type bool will be interpreted as string in the future
=> $tok might be false in Tokenizer.php
